### PR TITLE
feat: be able to serialize json object in kafka

### PR DESCRIPTION
**Pull request by nkhalis**

### CODE REVIEW

**Comment by brian-mulier** [comment]
Hello !
Is there any reason not to use the avro consumers / producers for your usecase ?

**Comment by nkhalis** [comment]
We'd like to serialize object as json in kafka (not as string nor avro) so that we could use our kafkaTemplate and producers as follow:
```
var stock = new Stock();
kafkaJsonTemplate.send(new ProducerRecord<>("topic_name", stock));
```

```
@KafkaListener(...)
    public void receiveLinqueoMessage(@Payload List<Stock> messagePayloads, ...) { }
```

At the moment, it is not possible since tzatziki assumes the payload is stored as string so we need to use jackson to convert object from POJO to String and vice versa.

**Comment by nkhalis** [comment]
however, it can be a good practice to convert our serializer to avro and create a dedicated schema registry

**Comment by brian-mulier** [comment]
LGTM although I can't test it from my side.
Make sure that it maintains the same behaviour for pure String objects.
@mimfgg any thing you see ?

**Comment by brian-mulier** [comment]
Especially with pure String but I think Jackson will handle it easily

**Review by brian-mulier — APPROVED** [review]

**Review by mimfgg — APPROVED** [review]

**Comment by brian-mulier** [comment]
@nkhalis feel free to merge when you tested it on your projects :+1:

**Comment by mimfgg** [comment]
@nkhalis any news on this one?

**Comment by mimfgg** [comment]
Should we close this one?

**Pull request closed without merging**
