### PR TITLE
fix: none spring web app crashing because no "@LocalServerPort"

### PR DESCRIPTION
**Pull request by mehdi-elketroussi**
- For non-web applications, spring web dependencies have been passed to the **provided** scope so as not to load them during the test phase.
- HttpInterceptor passed to **OnCondtionalWebApplication** because dependent on spring web, so non-web projects should not load it.
- For non-web projects, the **LocalServerPort** uses the @Value to have a default value.

### CODE REVIEW

**Review by brian-mulier — APPROVED** [review]
Hello !

Looks good to me, except that are you sure spring kafka and jpa still require webs dependencies ?

**Comment by mehdi-elketroussi** [comment]
Hello @brian-mulier , 

Spring kafka and jps style requires webs dependencies because of the application launched for tests

**Comment by mimfgg** [comment]
I'm not sure either. The jpa and Kafka modules work fine without the dependency. I remember us removing it so that we don't pull it in for everyone. Note that having it as `test` won't add it to the projects depending on those modules either. The users will have to add them as explicit dependencies anyway. Are you sure you are not just missing the dependency in your project?

**Comment by mehdi-elketroussi** [comment]
Since the dependence has passed to the Provided Scope in the Pom.xml of the Tzatziki-Spring project, the classes are no longer in the classpath of the Kafka and JPA project, you have to add for the tests of these projects. Otherwise UserController doesn't compile:
image

**Comment by mimfgg** [comment]
oh ... I understand now ... I was in holidays on my phone. It makes sense.

**Review by mimfgg — APPROVED** [review]

**Pull request merged**
